Update lambda
Snowflake-Labs/terraform-snowflake-aws-geff pull request #16
Opened 2021-06-10 10:33 UTC by sfc-gh-pkommini

Update lambda to latest code

2021-06-10 13:39 UTC, sfc-gh-cnakhate approved these changes

2021-06-10 13:54 UTC, sfc-gh-rgaikwad approved these changes

2021-06-10 22:15 UTC, sfc-gh-afedorov requested changes
don't undo the changes to Google API Client driver

2021-06-14 14:29 UTC, sfc-gh-pkommini commented on lambda-code/drivers/process_https.py
> +                'status': e.code,
There is no status. I got a `mypy` type error.

2021-06-14 14:34 UTC, sfc-gh-pkommini commented on lambda-code/drivers/process_google.py
> -    if authorized_user_info is not None:
@sfc-gh-afedorov We'll have to review together and merge. I didn't mean to remove this. I just copied the entire code from `geff_aws/lambda-code` module we had.

2021-06-14 15:15 UTC, sfc-gh-afedorov commented on lambda-code/drivers/process_google.py
> -    if authorized_user_info is not None:
oh, let's split this up into separate commits, then, so we make sure we understand what we are changing, then. I had been adding fixes to this and the `sfc-security` copy for awhile which will need to be merged here.

2021-06-14 15:16 UTC, sfc-gh-afedorov commented on lambda-code/drivers/process_https.py
> +                'status': e.code,
weird, iirc the documentation right, the error and response should have identical interfaces, would be curious to find out what the difference is, but not urgent.

2021-06-14 15:17 UTC, sfc-gh-afedorov commented
esp since we do not have tests, let's re-make these changes in small chunks we can be confident aren't breaking anythign.

2021-06-14 15:17 UTC, closed without merging

2021-06-14 17:43 UTC, sfc-gh-pkommini commented on lambda-code/drivers/process_https.py
> +                'status': e.code,
These are the [docs](https://docs.python.org/3/library/urllib.error.html)

2021-06-15 00:47 UTC, sfc-gh-afedorov commented on lambda-code/drivers/process_https.py
> +                'status': e.code,
ya, they're pretty vague with "Though being an exception [...] an HTTPError can can also function as [...] the same thing that urlopen() returns", but fwiw the implementation is true to that wording —

~~~
In [10]: try:
    ...:     response = urlopen(Request('https://api.abuseipdb.com/api/v2/check', method='POST'))
    ...: except Exception as e:
    ...:     response = e
    ...: 

In [11]: response
Out[11]: <HTTPError 405: 'Method Not Allowed'>

In [12]: response.code
Out[12]: 405

In [13]: response.status
Out[13]: 405
~~~

All good either way, interesting choice